import requests
from datetime import datetime
import smtplib


MY_LAT = 49.269909 # Your latitude
MY_LONG = -123.153236 # Your longitude

# Function that returns TRUE if your position is within +5 or -5 degrees of the ISS position.
def is_iss_overhead():
    # Get data from API
    response = requests.get(url="http://api.open-notify.org/iss-now.json")
    response.raise_for_status()
    data = response.json()

    iss_latitude = float(data["iss_position"]["latitude"])
    iss_longitude = float(data["iss_position"]["longitude"])

    # # Debugging
    # print("\n==============ISS==============")
    # print(f"ISS_longitude: {iss_longitude}")
    # print(f"My longitude: {MY_LONG}\n")
    # print(f"ISS_latitude: {iss_latitude}")
    # print(f"My latitude: {MY_LAT}\n")
    # MY_LAT = iss_latitude # Your latitude
    # MY_LONG = iss_longitude # Your longitude

    lower_lat = MY_LAT - 5
    upper_lat = MY_LAT + 5
    lower_long = MY_LONG - 5
    upper_long = MY_LONG + 5
    if (lower_lat <= iss_latitude <= upper_lat) and (lower_long <= iss_longitude <= upper_long):
        print("ISS location within range.")
        return True
    # Don't actually require the "else"
    else:
        print("ISS latitude is not withing range.\n")
        return False


def is_night():
    # Dictionary
    parameters = {
        "lat": MY_LAT,
        "lng": MY_LONG,
        "formatted": 0,
    }
    response = requests.get("https://api.sunrise-sunset.org/json", params=parameters)
    response.raise_for_status()
    data = response.json()
    sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])
    sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])
    # sunset = data["results"]["sunset"].split("T")[1]
    # time_now = datetime.now()
    hour_now = datetime.now().hour
    # print(f"hour_now: {hour_now}")
    # print(f"sunset: {sunset}")

    if hour_now >= sunset or hour_now <= sunrise:
        # print("Dark out")
        return True
    else:
        # print("Light out")
        return False

def send_email():
    # Define the sender's email address and password (App Password generated by Google)
    my_email = "rhyder.sharpe@gmail.com"
    password = "desqcbrcqnjkrxwc"

    # Establish a secure connection to the Gmail SMTP server
    with smtplib.SMTP("smtp.gmail.com") as connection_gmail:
        connection_gmail.starttls()  # Secure connection
        connection_gmail.login(user=my_email, password=password)
        # Send the email with the customized letter
        connection_gmail.sendmail(
            from_addr=my_email,
            to_addrs=my_email,
            msg=f"Subject:Hello\n\n The ISS is above Kitsilano!"
        )



if is_iss_overhead() and is_night():
    print("Look up. The ISS is above")
    send_email()
# else:
#     print("It is to bright to see the ISS or its to far away")





#If the ISS is close to my current position
# and it is currently dark
# Then send me an email to tell me to look up.
# BONUS: run the code every 60 seconds.
